/**
 * OpenAI-compatible image generation (POST {baseUrl}/images/generations) for
 * self-hosted / third-party endpoints — the BYOK counterpart to gskGenerateImage.
 * Runs in the Electron main process (plain Node fetch, rides the undici proxy
 * dispatcher installed by the shell bootstrap).
 *
 * Generated bytes never travel back as data: URLs (they would leak into model
 * context through tool-result text) and never as raw file:// paths (a
 * renderer-supplied file path would be an arbitrary-read primitive). Instead
 * the bytes are stashed in a bounded in-memory map and referenced by a
 * `genimage://<id>` URL that only this module can resolve — the renderer's
 * existing ai:fetch-image hop fetches it like any remote image.
 */

export interface ImageApiConfig {
  baseUrl: string
  apiKey: string
  model: string
}

export interface GeneratedImageBytes {
  base64: string
  mime: string
}

const GENERATE_TIMEOUT_MS = 300_000
/** ~64MB of decoded image bytes cached across a run; the oldest entry is evicted */
const STASH_MAX_TOTAL_BYTES = 64 * 1024 * 1024
export const GENIMAGE_SCHEME = 'genimage://'

interface StashedImage {
  base64: string
  mime: string
  bytes: number
  at: number
}

const stash = new Map<string, StashedImage>()
let stashSeq = 0

/** Store generated bytes; returns the opaque URL handed back through the tool result. */
export function stashGeneratedImage(base64: string, mime: string): string {
  // one entry per tool call is plenty; dropping the whole cache on overflow
  // keeps the bound trivial and the freshest call is always the survivor
  const bytes = base64.length
  if (bytes > STASH_MAX_TOTAL_BYTES) {
    throw new Error(`generated image too large to cache (${Math.round(bytes / 1024 / 1024)}MB)`)
  }
  if ([...stash.values()].reduce((n, s) => n + s.bytes, 0) + bytes > STASH_MAX_TOTAL_BYTES) {
    stash.clear()
  }
  const id = `${Date.now().toString(36)}-${(stashSeq++).toString(36)}-${Math.random().toString(36).slice(2, 8)}`
  stash.set(id, { base64, mime, bytes, at: Date.now() })
  return `${GENIMAGE_SCHEME}${id}`
}

/** Resolve a `genimage://` URL produced by stashGeneratedImage; null when unknown/expired. */
export function takeStashedImage(url: string): GeneratedImageBytes | null {
  if (!url.startsWith(GENIMAGE_SCHEME)) return null
  const id = url.slice(GENIMAGE_SCHEME.length)
  const hit = stash.get(id)
  if (!hit) return null
  // entries live for 10 minutes — plenty for the immediate fetch-image hop
  if (Date.now() - hit.at > 10 * 60_000) {
    stash.delete(id)
    return null
  }
  return { base64: hit.base64, mime: hit.mime }
}

interface ImageApiResponse {  data?: Array<{ b64_json?: unknown; url?: unknown }>
  error?: { message?: unknown } | string
}

/**
 * Generate one image via an OpenAI-compatible images endpoint. Accepts both
 * response shapes: gpt-image-1's always-base64 `b64_json` and dall-e-style
 * `url` results (the URL is downloaded here, in the main process).
 */
export async function openaiCompatibleGenerateImage(
  cfg: ImageApiConfig,
  prompt: string,
  signal?: AbortSignal,
): Promise<GeneratedImageBytes & { url: string }> {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), GENERATE_TIMEOUT_MS)
  const onAbort = () => controller.abort()
  signal?.addEventListener('abort', onAbort, { once: true })
  try {
    const resp = await fetch(`${cfg.baseUrl.replace(/\/$/, '')}/images/generations`, {
      method: 'POST',
      signal: controller.signal,
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${cfg.apiKey}`,
      },
      body: JSON.stringify({ model: cfg.model, prompt, n: 1 }),
    })
    const text = await resp.text()
    if (!resp.ok) {
      throw new Error(`Image API HTTP ${resp.status}: ${text.slice(0, 200)}`)
    }
    let json: ImageApiResponse
    try {
      json = JSON.parse(text) as ImageApiResponse
    } catch {
      throw new Error(`Image API returned an unparseable body: ${text.slice(0, 200)}`)
    }
    if (json.error) {
      const msg = typeof json.error === 'string' ? json.error : String(json.error.message ?? 'unknown error')
      throw new Error(`Image API error: ${msg}`)
    }
    const item = json.data?.[0] ?? {}
    if (typeof item.b64_json === 'string' && item.b64_json) {
      return finish(item.b64_json, 'image/png')
    }
    if (typeof item.url === 'string' && item.url) {
      if (!/^https:\/\//i.test(item.url)) {
        throw new Error(`Image API returned a non-https URL: ${item.url.slice(0, 120)}`)
      }
      const dl = await fetch(item.url, { signal: controller.signal })
      if (!dl.ok) throw new Error(`Image download failed: HTTP ${dl.status}`)
      const buf = Buffer.from(await dl.arrayBuffer())
      const mime = (dl.headers.get('content-type') ?? 'image/png').split(';')[0]!.trim()
      return finish(buf.toString('base64'), mime)
    }
    throw new Error(`Image API returned no image data: ${text.slice(0, 200)}`)
  } finally {
    clearTimeout(timer)
    signal?.removeEventListener('abort', onAbort)
  }
}

/** Cache the bytes and wrap the genimage:// reference as the tool-facing result. */
function finish(base64: string, mime: string): GeneratedImageBytes & { url: string } {
  return { base64, mime, url: stashGeneratedImage(base64, mime) }
}
